# Generated by Django 4.0.4 on 2022-04-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='mobile_money_number',
            field=models.CharField(default='0971977252', help_text='Mobile Money number where you want to receive funds for the event.', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='banner_image',
            field=models.ImageField(default='banner.png', upload_to='BannerImages', verbose_name='Upload a Banner Image for this Event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='sitting_plan',
            field=models.ImageField(upload_to='SittingPlans'),
        ),
        migrations.AlterField(
            model_name='eventticket',
            name='ticket_number',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
