# Generated by Django 4.0.4 on 2022-07-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='children_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='east_wing_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='grand_stand_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='lower_east_blue',
            field=models.FloatField(blank=True, null=True, verbose_name='Lower East Blue'),
        ),
        migrations.AddField(
            model_name='event',
            name='lower_north_orange',
            field=models.FloatField(blank=True, null=True, verbose_name='Lower North (Orange)'),
        ),
        migrations.AddField(
            model_name='event',
            name='lower_south_orange',
            field=models.FloatField(blank=True, null=True, verbose_name='Lower South (Orange)'),
        ),
        migrations.AddField(
            model_name='event',
            name='north_wing_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='open_wing_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='south_wing_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='upper_east_blue',
            field=models.FloatField(blank=True, null=True, verbose_name='Upper East Blue'),
        ),
        migrations.AddField(
            model_name='event',
            name='upper_north_orange',
            field=models.FloatField(blank=True, null=True, verbose_name='Upper North (Orange)'),
        ),
        migrations.AddField(
            model_name='event',
            name='upper_south_orange',
            field=models.FloatField(blank=True, null=True, verbose_name='Upper South (Orange)'),
        ),
        migrations.AddField(
            model_name='event',
            name='west_wing_blue',
            field=models.FloatField(blank=True, null=True, verbose_name='West Wing (Blue)'),
        ),
        migrations.AddField(
            model_name='event',
            name='west_wing_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='vip_ticket_price',
            field=models.IntegerField(blank=True, help_text='Price is in Zambian Kwacha (ZMW)', null=True, verbose_name='VIP Ticket Price'),
        ),
        migrations.AlterField(
            model_name='event',
            name='vvip_ticket_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='VVIP Ticket Price'),
        ),
    ]
