# Generated by Django 4.0.4 on 2022-04-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_mobile_money_number_alter_event_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.CharField(max_length=30, verbose_name='Who is the Organizer of this Event?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(help_text='Please specify the name of the place.', max_length=30),
        ),
    ]
