# Generated by Django 4.0.2 on 2022-03-10 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_town_alter_eventticket_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date_time_published',
        ),
    ]
