# Generated by Django 4.0.4 on 2022-04-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_organizer_alter_event_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='KazangSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_uuid', models.CharField(editable=False, max_length=255)),
                ('date_time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
