# Generated by Django 4.0.4 on 2022-04-23 00:34

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_kazangsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue_location',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True),
        ),
    ]
