# Generated by Django 4.0.2 on 2022-03-13 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_date_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventticket',
            old_name='client_first_name',
            new_name='client_full_name',
        ),
        migrations.RemoveField(
            model_name='eventticket',
            name='client_last_name',
        ),
    ]
