# Generated by Django 4.0.4 on 2022-04-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='address',
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_location',
            field=models.CharField(blank=True, help_text='Please paste the google maps coordinates', max_length=50, null=True),
        ),
    ]
