# Generated by Django 4.0.2 on 2022-03-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_rename_client_first_name_eventticket_client_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventticket',
            name='client_phone_number',
            field=models.CharField(default='0971977252', max_length=14),
            preserve_default=False,
        ),
    ]
