# Generated by Django 4.0.4 on 2022-04-22 15:40

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsandconditions',
            name='buyer_terms_and_conditions',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Elaborate the Terms and Conditions Buyers are subjects to. Please be clear in your explanation.'),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='event_organizer_terms_and_conditions',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Terms and Conditions for Event Owners. This must be clear and straight forward to understand.'),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='privacy_policy',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Describe how you shall maintain security on the information that users are proving to All1Zed Events Platform. '),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='terms_of_use',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='By using All1Zed Events Platform, all stakeholders agree to your specific terms. Describe them here.'),
        ),
    ]
