# Generated by Django 4.0.4 on 2022-04-25 14:52

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0002_alter_termsandconditions_buyer_terms_and_conditions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsandconditions',
            name='privacy_policy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Describe how you shall maintain security on the information that users are proving to All1Zed Events Platform.', null=True),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='terms_of_use',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='By using All1Zed Events Platform, all stakeholders agree to your specific terms. Describe them here.', null=True),
        ),
    ]
